### PR TITLE
Topic/auth

### PR DESCRIPTION
**Pull request by aj-michael**
Things that need to be accomplished in this pull request:
- [x] Allow developers to generate new private keys
- [x] Save public keys in database
- [x] Allow developers to specify auth URL per application
- [x] Allow developers to whitelist email addresses if using pathfinder auth
- [x] Allow developers to remove email addresses from the whitelist.
- [x] Update Pathfinder.js
- [x] Pass Google ID tokens to Pathfinder.js to display the dashboard.

### CODE REVIEW

**Comment by aj-michael** [comment]
Ok, all of the intended features are now complete and ready for review.

Also, they are live on https://thepathfinder.xyz.

**Comment by danhanson** [comment]
It does not look like you ever save the public key in the application table. We need to do this in order to allow custom authentication.

**Comment by aj-michael** [comment]
@danhanson , I do save it. Look at DashboardController.java line 50

**Comment by danhanson** [comment]
oh yeah you do ok

**Comment by aj-michael** [comment]
Thanks :+1:

**Pull request merged**
