### PR TITLE
Topic/betterwebsite

### PR DESCRIPTION
**Pull request by aj-michael**
This is step one of my redesign of the website. Its going to be a ton of code changes, so I figured I would open this sooner than later.

### CODE REVIEW

**Comment by aj-michael** [comment]
I am not going to publish this for a while, because I believe web server has not been updated to reflect DB schema changes. Just working on the UI atm.

**Comment by aj-michael** [comment]
@robinsdm , This is now live on http://thepathfinder.xyz

It is definitely not a finished site, but the  routes resolve correctly and the evolutions do not crash with dan's DB changes. I think this is an appropriate point for you to review/merge.

**Comment by aj-michael** [comment]
There is a bug on the current live site where the page loads in the middle. I fixed it in a new commit, but it is not released to production.

**Comment by aj-michael** [comment]
Also, David when you review this try clicking sign in and then logging in (log in is not hooked up yet).

**Comment by robinsdm** [comment]
The website looks really nice. I just want to make sure the pictures don't end up being copyrighted.

**Comment by aj-michael** [comment]
They're not. I took them from free stock photo sites.

**Pull request merged**
