### PR TITLE
Oops, messed up v0.1.1. Time for v0.1.2!

### PR DESCRIPTION
**Pull request by aj-michael**
David, please merge this when you can confirm that the new features are live.

### CODE REVIEW

**Comment by aj-michael** [comment]
http://146.148.57.117:9000/

**Comment by aj-michael** [comment]
Well this one's borked too.

**Comment by robinsdm** [comment]
Tell me when you get it up.

**Comment by aj-michael** [comment]
Well, dan's code doesn't work, and you depend on that IP address. So we're blocked on dan.

**Comment by aj-michael** [comment]
Dan's server is now up at http://130.211.184.70:9000/

He hasn't confirmed that it works yet, but I'm going to re-release yours anyways.

**Comment by robinsdm** [comment]
Ok, mine seems to work thanks.

**Pull request closed without merging**
