### PR TITLE
The password should be ignored now

### PR DESCRIPTION
**Pull request by robinsdm**

### CODE REVIEW

**Comment by aj-michael** [comment]
This is in reference to issue #15. David, could you add a test the confirms that there is no password field in the response now?

**Comment by aj-michael** [comment]
I haven't actually verified that this works, but I need to release this server immediately so that we have applications in postgres, so I am taking your word that it works.

**Comment by robinsdm** [comment]
It works when I test it with postman.

**Comment by aj-michael** [comment]
I think your get applications endpoint is broken.

This is the live site from dev: http://146.148.57.117:9000/getapplications

**Comment by robinsdm** [comment]
I works on my dev branch,

**Comment by aj-michael** [comment]
The link I posted is dev branch

**Pull request merged**
